version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-proxy-network
    env_file:
      - ./nginx/.env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

networks:
  nginx-proxy-network:
    driver: bridge
